### ISSUE TITLE
Refine allocation of simulations across processors?

### ISSUE THREAD

**Issue by droodman** [gvegayon/parallel#101]
I just used parallel sim to spread 10 simulations across seven processors. It appears to me that it allocated 1 simulation each to six of the processors and allocated the remaining four to the 7th processor. Total run time was the time cost of running four simulations in sequence. But it seems like with a better allocation, total run time would have 2X instead of 4X the time cost of a single simulation.

If this is correct, I can imagine the algorithm that leads to this allocation. It works fine when the number of simulations is much larger. But it looks pretty inefficient for a small number of simulations.

Thanks for this package! It's extremely useful.

**Comment by gvegayon** [comment]
That is interesting. The algorithm to distribute simulations should be able to make the distribution as even as possible. Can you provide a reproducible example with your ten simulations? The core principle is that parallel will split the simulations/data and call independent stata instances to run the tasks. The job of how those tasks are distributed across processors depends on the CPU.

**Comment by droodman** [comment]
```
clear all

program define sim, rclass
  return scalar instance = $pll_instance
end

parallel initialize 7
parallel sim, reps(10): sim
list
```

Output in Stata 16.1 MP in Windows 11:

```
     +----------+
     | instance |
     |----------|
  1. |        7 |
  2. |        7 |
  3. |        7 |
  4. |        7 |
  5. |        6 |
     |----------|
  6. |        5 |
  7. |        4 |
  8. |        3 |
  9. |        2 |
 10. |        1 |
     +----------+

```

**Comment by gvegayon** [comment]
Thanks for the example. Right now, I can't think of a quick fix. At most, you could write a program that leverages the local variables generated within each parallel instance (e.g., `$pll_instance`), as you are in your example. If you can think of a way to fix it, please share it here. We welcome PRs :).
