### ISSUE TITLE
parallel sim allocation of tasks

### ISSUE THREAD

**Issue by carlosmolinaguerra** [gvegayon/parallel#105]
I think the allocation of tasks in the parallel sim can be improved.
I wanted to do a simulation with 1000 repetitions. I have 206 processors on my server. I noticed that if I use them all, this takes a while because of the way in which the tasks are assigned to the processors. In particular, I think what the program does is that it assigns 4 tasks to 205 processors and the remaining 180 tasks to 1 processor and this task would take a really long time. 
Clearly, it is more efficient for me to just use 200 processors. My concern is that not anyone is going to see this immediately and I suggest that you improve this (in my case, this should automatically allocate between 4 and 5 tasks per processor).

**Comment by gvegayon** [comment]
OK, #103 was merged. Give it a try. If the problem persists, please reopen this issue.
