### ISSUE TITLE
_pllcxxxx.do was interrupted. Would you like the batch job to continue

### ISSUE THREAD

**Issue by yanyu2015** [gvegayon/parallel#111]
system: win 11
stata version: stata 18

code:
```
capture program drop parforreg
prog def parforreg
	use "1.dta", clear
	forvalues i = 1/100 {
		qui reg Y X var1 var2 var3 var4
		qui matrix table1 = r(table)
		qui mat2txt, matrix(table1) saving("./`i'.csv") replace
	}
end

parallel setclusters 8
parallel, prog(parforreg) nodata: parforreg
```
This seems to be a problem with batch mode in stata?
The weird thing is that as long as I click yes, the program continues to execute and writes the file I want.

**Comment by bquistorff** [comment]
The child process runs in another window, and if you try to select it,
you'll get a message like this, at least on Windows. I think this is a
property of Stata. Are you somehow trying to select that child process
window?

**Comment by yanyu2015** [comment]
On Windows, after the `parallel` command is executed, it indeed opens multiple Stata windows. However, I did not interact with any of the windows by clicking on them. At this point, **the program got stuck**, so I had to click on the newly generated Stata windows to see what was happening. That’s when I discovered this dialog box prompting me to choose whether to continue or not.

**Comment by yanyu2015** [comment]
Thank you for your answer. I've discovered that as long as I don't click on the window and wait for the program to finish running, it will close automatically without any action needed on my part. But I have a new question that I hope you can help me with. @bquistorff
