### ISSUE TITLE
Parallel fails when working directory is network location (UNC)

### ISSUE THREAD

**Issue by epkugelmass** [gvegayon/parallel#12]
The windows batch file that parallel creates and calls will exit with errors if the working directory in Stata is a network location (e.g. \\\server\share). This is because CMD.EXE does not support the "Universal Naming Convention."

The solution is to call the Windows temporary network drive creator, 'popd'.

See http://superuser.com/questions/282963/can-you-browse-a-unc-path-using-a-command-line-environment-without-mapping-it-to

**Comment by gvegayon** [comment]
Hi epkugelmass! What about parsing the paths before writing down the .bat file?? Thanks for your contribution

**Comment by epkugelmass** [comment]
I think using the popd/pushd system is the way to go.

Otherwise, you need to manually map a network drive and make sure you are using a letter that is as yet unassigned.

popd/pushd takes care of the whole thing by itself. Totally abstracted.

I can submit a patch if you'd like.

**Comment by gvegayon** [comment]
That'll be great!
