### ISSUE TITLE
Parallel does not execute profile.do

### ISSUE THREAD

**Issue by epkugelmass** [gvegayon/parallel#13]
Stata allows the creation of a profile.do that will run every time Stata is initialized.
http://www.stata.com/manuals13/gswb.pdf#B.3ExecutingcommandseverytimeStataisstarted

This is useful because it allows users to override system preferences. This is particularly important when the ADOPATH is solely composed of write-restricted system directories. Parallel should include an option for each cluster to call profile.do. When this is not done, Parallel might not be found by the clusters.

For example:
* ADOPATH is C:/ado/
* User profile do: sysdir set personal C:/Users/jim/Stata
* User installs parallel (to personal part of ADOPATH)
* User calls parallel, parallel creates batch file
* Batch file calls 'Stata do ...'. Profile.do is not run.
* Call to parallel fails because cluster-do files fail: parallel mata library is not found

**Comment by bquistorff** [comment]
The -parallel setclusters- command allows an includefile(filename) option where you can pass in a file with preferences. Does that work for you? -parallel- should copy over the ADOPATH (and rescan for mlibs), but it won't copy over all preferences.

Somewhat tangentially, is the problem that any call to Stata in batch-mode on Windows fails to load the profile.do?

As a work around

**Comment by epkugelmass** [comment]
Yes, this works for me. The version on ssc does not yet have includefile() 
@gvegayon: your website appears to be down (tried ssc install from there...failed.)

**Comment by gvegayon** [comment]
Yes, it is down, try using the installer from github raw

**Comment by bquistorff** [comment]
To answer my own question, Stata in batch mode on windows does appear to normally load the user profile.do.

**Comment by bquistorff** [comment]
I'm closing this. I don't think it would be a good idea to have each cluster read profile.do. We should be aiming to replicate in the clusters the environment at the time of the call to `parallel`, not the environment at the startup of Stata.
