### ISSUE TITLE
Create help files for debugging ('How to debug')

### ISSUE THREAD

**Issue by gvegayon** [gvegayon/parallel#15]
These could be sthlp files with common FAQs about what to do when things go wrong (basically when there's a problem in some of the clusters' code or when Stata shuts down).

This will be mainly a guide for novice experts on how to: (1) Track errors on Stata using parallel; (2) Kill processes in the different OSs. The second part, as Brian suggested, can be aided providing a command to list Stata processes that are currently running and that may have something to do with parallel. In linux can be something like

ps -aux | grep -regexp '__pll[a-z0-9]+_do'

Read that into stata, parse it using regexp and then return the processes names/pids and a link to run the command in bash 'kill 00000'.

**Comment by bquistorff** [comment]
Is this still needed as the parent Stata now tracks child processes and kills them when the user breaks in the parent process?

**Comment by gvegayon** [comment]
I guess only the part on how to debug code using "parallel printlog" and "viewlog". Or are we been to nice :P?

**Comment by bquistorff** [comment]
OK. I'll make sure we mention this is mentioned in the help file.

**Comment by gvegayon** [comment]
Great! Thanks

George G. Vega Yon
+1 (626) 381 8171
http://www.its.caltech.edu/~gvegayon/
