### ISSUE TITLE
Parallel on Windows does not respect STATATMP environmental variable

### ISSUE THREAD

**Issue by epkugelmass** [gvegayon/parallel#16]
parallel does not respect the STATATMP variable, which takes precedence over TEMP when it exists.

http://www.stata.com/support/faqs/data-management/statatmp-environment-variable/

Walkthrough:
1. System environment variable STATATMP is D:\temp
2. Parallel writes batch file with `set TEMP...` instead of `set STATATMP`
3. Stata ignores the new TEMP because STATATMP exists.

Solution:
https://github.com/gvegayon/parallel/blob/master/ado/parallel_run.mata#L85
Replace TEMP= with STATATMP=

This will always work.

Can I submit a patch?

**Comment by bquistorff** [comment]
It looks like we additionally use TEMP in the Unix section (L73), which I think should also be changed.  With that, a patch would be welcome. Thanks.
