### ISSUE TITLE
parallel_setclusters() not found

### ISSUE THREAD

**Issue by PMitchDowney** [gvegayon/parallel#19]
Hello,

I installed parallel through ssc yesterday and it appeared to have installed properly, but I haven't been able to use it yet. When I run -- parallel setclusters 2 -- I get the following error:
 < istm t>:  3499  parallel_setclusters() not found

I'm using Stata 13.1 on a Windows machine and this occurs both on a computer with 3 cores and one with 24 cores. I'm not a computer expert, so please let me know if I'm missing something obvious or what additional information is needed. Thanks in advance for any guidance.

-Mitch

Note: This issue was also posted on the Statalist Forum on 13 August:
http://www.statalist.org/forums/forum/general-stata-discussion/general/1306137-parallel-package-problem-parallel_setclusters-not-found

**Comment by bquistorff** [comment]
Hi Mitch, that's a function that's in a compiled mlib. A few things to check:
- Was the mlib file was installed into STATADIR/ado/plus/l/lparallel.mlib (where STATADIR is probably something like "C:\Program Files (x86)\STATA13\")?
- Can Stata find the library? Is "lparallel" listed in -mata: mata mlib query- (Stata command)? If not, does -mata: mata mlib index- fix the problem?

**Comment by PMitchDowney** [comment]
Hi Brian,

Thanks for getting back to me. The file "lparallel.mlib" is not found in either of the following locations (the first is where ssc installs all the packages that I download, which I think is by default; the second is more similar to where you suggested I look):
-- C:\Program Files (x86)\ado\updates
-- C:\Program Files (x86)\Stata13\ado

I also searched my computer and no file "lparallel" with any file extension is found. That said, when I type --mata: mata mlib query-- then lparallel does show up in the list. I'm not sure how to interpret that.

To clarify, I have two computers: My "normal" 3-core computer that's internet connected, and a Stata server computer with 24 cores that's not internet connected. When I type "parallel setclusters 2" into the internet connected computer it now works fine. Yesterday, it didn't work in either. I don't understand what changed, unless someone updated ssc. The only other thing I can figure is that it's related to the number of instances of Stata that I had running when I tried yesterday?

But either way, I somehow need to find the "lparallel" file so that I can transfer it to the 24-core non-internet computer. When I type --mata: mata mlib query-- into that one, lparallel does NOT come up. I can transfer the file easily, but I cannot seem to find it.

Thanks again,
Mitch

**Comment by bquistorff** [comment]
You can see where Stata installs packages by typing -net query- and reading the 'ado' line. Since parallel is working on the internet machine, the files are there somewhere. I don't believe ssc was updated, so you probably had something weird going on with multiple sessions.

If you want to install the files manually to no-internet machine, then you will need multiple files. If you want to install the ssc version then download the files from [the ssc entry](https://ideas.repec.org/c/boc/bocode/s457527.html), put them somewhere immediately in your -adopath- (ie not in a subdir) like under PERSONAL, and redo the mlib index command. Alternatively you can download the dev version from github, which was directions in the readme for "download as zip and install" method. I'll close this since it's working on the internet machine.

**Comment by PMitchDowney** [comment]
Thanks Brian!

**Comment by fedehuneeus** [comment]
Hi @bquistorff, I'm having this same error. And I checked that all the parallel-related files are in the relevant ado folders (including checking in mata the lparallel.mlib file). any other ideas of what might be going on? I'm using StataMP 17. Thanks a lot!

**Comment by fedehuneeus** [comment]
Hi @bquistorff, I'm having this same error. And I checked that all the parallel-related files are in the relevant ado folders (including checking in mata the lparallel.mlib file). any other ideas of what might be going on? I'm using StataMP 17. Thanks a lot!

**Comment by gvegayon** [comment]
Hi @fedehuneeus, I think the answer is a bit outdated. The latest version of parallel is not on SSC but here. Try following the instructions to download it [directly from GitHub](https://github.com/gvegayon/parallel?tab=readme-ov-file#latest-version). HIH

**Comment by fedehuneeus** [comment]
great thanks!

**Comment by fedehuneeus** [comment]
hi @gvegayon, i'm still getting issues with using parallel. i installed directly with net install using the Github. although now setclusters does work, I'm still getting the error "3499 parallel_sandbox() not found". i tried running the compile.do from the ado/ folder and I got the following error: "3499 dt_moxygen() not found". Any ideas of how to solve this? Thanks!

**Comment by gvegayon** [comment]
Did you used `mata mata mlib index` after installation?

**Comment by fedehuneeus** [comment]
yes, and i see lparallel installed

**Comment by fedehuneeus** [comment]
yes, and i see lparallel.mlib installed

**Comment by gvegayon** [comment]
I'm running out of ideas. Try [this](https://github.com/gvegayon/parallel/issues/98#issuecomment-1187793374). Maybe @bquistorff could help?

**Comment by bquistorff** [comment]
Hmm... Maybe the old library was still in memory when you upgraded. I'd try to  `ado uninstall parallel`, restart the machine, then re-install using directions for GitHub (including the `mata mata mlib index` step), and then try running.

**Comment by fedehuneeus** [comment]
ok thanks!
