### ISSUE TITLE
Provide information on likely setcluster #

### ISSUE THREAD

**Issue by bquistorff** [gvegayon/parallel#20]
It would be nice if we could give a guess to the user as to what to number to put for -parallel setclusters-. That way if they type an empty -parallel setclusters- (with no number) or they try to use parallel without setting the cluster we can suggest a number and even print a command that they could click on. We could query the `c(processors_mach)` and have our guess be something like 75% of clusters until we max out at 8 (and if there are 2-3 processors then we guess 2).

**Comment by gvegayon** [comment]
Isn't that macro only available for MP? I've thought about this, perhaps we
can use this instead

https://social.technet.microsoft.com/Forums/windowsserver/en-US/1ca11e2e-32c5-4692-903e-bf38dfc38397/how-to-find-number-of-actual-processors-present-through-command-prompt?forum=winservergen

, This for Unix

https://social.technet.microsoft.com/Forums/windowsserver/en-US/1ca11e2e-32c5-4692-903e-bf38dfc38397/how-to-find-number-of-actual-processors-present-through-command-prompt?forum=winservergen

And I dont kmow for mac, I'll start working on something for unix and
windows!

George G. Vega Yon
+1 626 381 8171
http://www.its.caltech.edu/~gvegayon

**Comment by bquistorff** [comment]
For Unix, you are correct, but my Stata 13 SE on Windows does report it. So, some platform dependent solution would be needed.

**Comment by bquistorff** [comment]
I think this is covered by `setclusters default` now.
