### ISSUE TITLE
Allow commenting in the parallelized do-file

### ISSUE THREAD

**Issue by dvmasterov** [gvegayon/parallel#22]
Here's a toy example illustrating the problem. 

There are three files:
1) The main file pdo.do :
2) Two versions of a loop mydofile.do, run by pdo.do in parallel

The cr delimited one works, while the #delimited one does not. It seems to get stuck at waiting for the clusters to finish forever.

mydofile1.do (cr delimited):
set more off
parallel break
levelsof id, local(g)
foreach v of local g {
	preserve
		keep if id==`v'
		save "group_`v'.dta", replace
	restore
}

mydofile1.do (# delimited):
#delimit;
set more off;
parallel break;
levelsof id, local(g);
foreach v of local g {;
    preserve;
        keep if id==`v';
        save "group_`v'.dta", replace;
    restore;
};

pdo.do (main do file):
#delimit;
clear;
set more off;
!rm group_*.dta;
set obs 4;
gen id = _n;
expand 2 if mod(_n,2)==1 ;
gen x = uniform();
sort id x;
parallel setclusters 2;
parallel do "mydofile1.do", processors(8);
/ *parallel do "mydofile2.do", processors(8); */
list, clean noobs;
clear;
fs "group_*.dta";
append using `r(files)';
sort id x;
list, clean noobs;
ls;

**Comment by bquistorff** [comment]
Will it work if you reset the delimiter back to cr at the end of the called loop file?

**Comment by dvmasterov** [comment]
Yes, that worked nicely! Please consider this issue closed.
