### ISSUE TITLE
parallel not running on university server

### ISSUE THREAD

**Issue by alnahedh** [gvegayon/parallel#24]
Hello,
I am having issues running any command or instance with parallel in my university server with StataMP 13.
Everything runs fine on my personal computer. But I would like to utilize the power of the server to dramatically increase the speed of my work.

Here are the symptoms of the problem:
when I run the command in my personal computer, I see new cmd and stata windows equal to the number of clusters pop up and then close when the parallel command is successfully done with execution.
When I run the same command in the server, also StataMP 13, I see the same cmd and stata instances pop up but close two seconds later and the command stalls without giving errors, as if its running in an infinite loop even for primitive operations that should execute in micro seconds.

This led me to believe that maybe the fact that I dont have admin privileges on the server is causing this issue so I pointed all stata directiories  (ala sysdir and adopath) to be on a network drive that has a dropbox directory where I have full read/write privileges, but again the problem persists. Other user-written commands that warrant a read/write like "savesome" work fine on the server, so maybe this is not an admin write privileges issue, I don't know. 

It must also be noted that when I run my work from my personal computer, I also point everything to the same dropbox folder (on the local pc hard-drive, not a network directory) and its running fine.

Any clues what is going on?

Thanks!
Saad

**Comment by gvegayon** [comment]
Hi there. Could you provide the code that you are using??

Thanks!

**Comment by alnahedh** [comment]
thanks for the prompt reply,

I mainly would like to use it with reclink, a fuzzy string matching stata package.

Here is the code:

mata mata mlib index  
parallel setclusters 8, force
parallel: reclink firm_name address using unmatched, gen(matchscore) idu(idu) idm(idm)

this code matches the strings firm_name and address between the current data and the same variables found in unmatched.dta where idu and idm are the unique identifiers in each dataset. Myscore is a match score.

The code runs fine on my personal computer, but it stalls at when I execute parallel : reclink 
it initially opens the 8 cmd and 8 stata windows for four seconds but they close afterwards. the results screen doesn't show anything besides "Waiting for the clusters to finish" and i have to hit break..

I tried to run a simple bootstrap regression to make sure reclink isn't somehow causing the issue on the server (even though it runs fine on my computer), but I get the same symptoms.
parallel bs, reps(50): reg y x1 x2
with less than 1,000 obs I still get the infinite loop thing on the server whereas the parallel bs regressions runs ok on my personal computer. 

The server runs two Intel Xeon E5-2660 @ 2.20 GHz  (2 sockets, 20 cores, 40 logical processors)
So I tried the processor(#) option just in case with 0, 1, 2 but no success

**Comment by gvegayon** [comment]
As you suggested, It might have to do with privileges, in particular, handling the tmp folder of your system. Basically, `parallel` stores a bunch of files on the system's temp dirs (see https://github.com/gvegayon/parallel/blob/master/ado/parallel.sthlp#L487-L493), so if you don't have access there, it will cause you problems (as what you are mentioning).

To see where is your tempdir, type in stata `di c(tmpdir)`, and check if you have enough privileges to write there. By the way, what is the server's OS? I read windows but It wasn't clear for me.

**Comment by alnahedh** [comment]
Thanks for the suggestion,
I think it is unlikely,
I typed ```di c(tmpdir) ``` and stata reported 
```E:\Users\saal9283\AppData\Local\Temp\19/ ```
which is the same network drive that everything is running from (including stata)
I opened this directory and there are a bunch of uncleaned temp do and logfiles created by parallel.
I also made sure I have writing privileges there, I could write and delete any of those files with no problems.

so my guess is maybe the parallel command is trying to write on the native C drive (where I do not have any writing privileges)?

the OS on the server is Windows Server2012 R2, but I doubt its the issue since I ran into the same issue with another university server running Windows Server2008 R1

**Comment by gvegayon** [comment]
If you could attach the resulting log files, do files and a file called something like __pll[asdasd]finito it'll be really useful.

**Comment by alnahedh** [comment]
Here's an archive with everything generated in that temp directory. I deleted all the old files and ran a new instance of parallel on the server to give you a clean set of logs with one iteration using reclink.

https://www.dropbox.com/s/iqo0evv8gqygg1f/logs.zip?dl=0

I suspect there might be an issue caused by dropbox since there are some dropbox denominated files created.

Thanks again for your help.

**Comment by alnahedh** [comment]
update:
I closed/shutdown dropbox on the server and ran the command again.. same thing, so it seems like not a dropbox related issue.. the second batch of logs for this troubleshoot can be found here:
https://www.dropbox.com/s/iqqt9xki6w9q0zm/logs2.zip?dl=0

**Comment by alnahedh** [comment]
nevermind,
please disregard the earlier files (deleted), I realized they were not what you are looking for.. sorry..
I believe these are the logs you are looking for:
https://www.dropbox.com/s/y59yjp2wbivpi1m/logs3.zip?dl=0

they do have errors of the sort
```. /* Checking for break */
. mata: parallel_break()
                 <istmt>:  3499  parallel_break(
> ) not found
r(3499);

end of do-file
r(3499);```

and such, I think these might be more helpful to nail down the issue..

thanks again

**Comment by gvegayon** [comment]
I see what's the problem. You need to install parallel in your server as well. Copying the ados and mlib files is not enough, try doing this

```stata
net install parallel, from(https://raw.github.com/gvegayon/parallel/master/) replace
mata mata mlib index
```

That should work

**Comment by alnahedh** [comment]
That's what I have done from the start,
but just in case I deleted everything and installed parallel and tuples the way you said with mata again, but it didn't work, the log files are still pointing to the same error:
```
. local result = _rc

. if (c(rc)) {
. cd "E:\Users\saal9283\stata\data/"
. mata: parallel_write_diagnosis(strofreal(c("rc")),"E:\Users\saal928
> 3\stata\data/__pll53wyaieu21_finito0002","while setting memory")
. clear
. exit
. }

. 
. /* Checking for break */
. mata: parallel_break()
                 <istmt>:  3499  parallel_break() not found
r(3499);

end of do-file
r(3499);
```

I tried setting the adopaths (BASE and PLUS) to all possible different permutations of directories (native C:\,      Netowork E:\,       and network E:\ inside dropbox)
but they all fail and point to the same error, 
I must mention that with the native C:\ drive I can only access BASE adopath. When I try to install parallel on C:\ in PLUS it understandably fails due to lack of writing privileges, so I am always forced to install parallel onto E:\ in PLUS directory

I could probably ask the network admin to install parallel onto C:\ in the PLUS adopath but I am not sure if they'd let me do that, and if they did the tempvars writing onto C:\ will most certainly fail..

I am also surprised that stata didnt break the execution despite the errors found in the log files.. it's pretty puzzling..

**Comment by gvegayon** [comment]
The problem is that the options that you pass on to stata are not passed by parallel in the child processes. Therefore, you can't change the adopath in your session and expect that to be reflected in the clusters. What I suggest, as you already said, is to install parallel in the `c(sysdir_plus)` dir and try from there.

**Comment by alnahedh** [comment]
I see,
I will ask the admin and update this thread if I had any success.. otherwise I'd just wait for the new update once you add it.
I sincerely appreciate the efforts, this package is by far one of the most useful user-written packages and it saves people hours of unnecessary waiting.

**Comment by gvegayon** [comment]
Brian just reminded me about the includefile option in parallel
setclusters. Try using that

George G. Vega Yon
+1 626 381 8171
http://www.its.caltech.edu/~gvegayon

**Comment by alnahedh** [comment]
May I ask for additional explanation for this option?
I read the option for includefile in the help file but I still don't get how it'd fit my case?
specifically, what file should I pass inside the parenthesis? can you kindly provide a simple example? 

Thanks

**Comment by alnahedh** [comment]
update:
the includefile() option worked like magic!
I pointed it to a do file with ``` sysdir set ``` settings,

thanks for the suggestion

Saad
