### ISSUE TITLE
include(path or cmd) option

### ISSUE THREAD

**Issue by gvegayon** [gvegayon/parallel#25]
In order allow the user to run commands before parallel starts, like setting the adopath, running an algorithm, etc.

**Comment by bquistorff** [comment]
Will the `includefile(filename)` options serve this purpose?

**Comment by gvegayon** [comment]
You are right! I forgot about that! Will this work in case stata can't find parallel.mlib??

**Comment by bquistorff** [comment]
Well, anytime you reset the adopath you should `mata: mata mlib index`. 

We automatically copy over PERSONAL and S_ADO (and reset mlibs), so the includefile likely doesn't have to be used for that.

**Comment by gvegayon** [comment]
It did worked. It was used to solve this problem
https://github.com/gvegayon/parallel/issues/24#issuecomment-156743478
