### ISSUE TITLE
Trouble with reshaping

### ISSUE THREAD

**Issue by suanalyst** [gvegayon/parallel#26]
I just ran across parallel and I'm trying to use it to speed up some reshaping.  But I keep getting the following error:
parallel setclusters 4
N Clusters: 4
Stata dir:  C:\Program Files (x86)\Stata13/StataSE-64.exe
parallel, by(Emplid) force: reshape long Q, i(Emplid) j(Question) string
file __pllv1erujp610_dataset.dta could not be opened
r(603);
I'm running Stata13 on a windows pc.  
Any advice?  Thanks!!

**Comment by gvegayon** [comment]
It seems to be a user privileges issue. Can you submit the output of the
command  cereturn list? Thanks

George G. Vega Yon
+1 (626) 381 8171
http://www.its.caltech.edu/~gvegayon/

**Comment by gvegayon** [comment]
Have you solved this?

Thanks

**Comment by bquistorff** [comment]
Closed until further information is provided.
