### ISSUE TITLE
Default behavior on error

### ISSUE THREAD

**Issue by bquistorff** [gvegayon/parallel#36]
I wanted to discuss the possibility of changing the behavior of `parallel` when there is an error in the clusters. Currently a message is displayed and a value is returned in `r()`. Most commands, however, exit with an error when not being able to run. Why is it that `parallel` doesn't display a message and then throw an error?

**Comment by gvegayon** [comment]
Sounds like a better option. I don't recall why I did it that way, but it actually doesn't make sense to not throw an error if there is one in any of the clusters. Let's do it that way.

**Comment by bquistorff** [comment]
Done.
