### ISSUE TITLE
Allow parent Stata process to terminate child Stata processes

### ISSUE THREAD

**Issue by bquistorff** [gvegayon/parallel#38]
One way that we can make `parallel`izing existing code easier is by having `break` work like it does in the normal setup. I think we should allow the parent process to forcefully terminate child processes without having users add `parallel break` commands to their code (they might not even be able to find locations where they can make it responsive). We would have to keep track of the child process IDs, but there's already some code to do this.

In fact I think this should be the default response to a user `break`, but we can deal with that once the feature is implemented. The details will differ across platforms so we might want to keep around the existing system as a fall-back.

**Comment by gvegayon** [comment]
That is what I wanted to accomplish/had in mind. Do you have code for this?

George G. Vega Yon
+1 (626) 381 8171
http://www.its.caltech.edu/~gvegayon/

**Comment by bquistorff** [comment]
The `winproc` branch does it.

**Comment by gvegayon** [comment]
So is it working for windows only? Or did you implemented it for Win/OSX/Unix?

**Comment by bquistorff** [comment]
That branch only has it working for Windows. We may be able to do the same stuff in the other OSes without plugins.

**Comment by gvegayon** [comment]
I think I got it work (partially) here: https://github.com/gvegayon/parallel/commit/eb9788d40a17ce9f16040dd6e75a7b548bd78380 now a file called __pll[parallelid]_pids is generated on OS != Windows. Will include changes after merging with your new branch.

**Comment by bquistorff** [comment]
Great! I've expanded upon it so that mata reads in the PIDS. It should be ready to go once we merge the winproc branch.

**Comment by bquistorff** [comment]
Done on c6bb22f.
