### ISSUE TITLE
Make guidelines for contributing

### ISSUE THREAD

**Issue by bquistorff** [gvegayon/parallel#39]
We might want to have some guidelines for contributing, specifically issue templates for standardizing reports. See GitHub's [documentation](https://help.github.com/articles/helping-people-contribute-to-your-project/). We might also want to have the other documents too.

**Comment by gvegayon** [comment]
Done with https://github.com/gvegayon/parallel/commit/eeffda34a36897beec66b4a2e61026ee877c4727 Need to create one for contributing with patches (and perhaps references on parallel).

One thing that might also be important is to keep track of modules using parallel so we can test them before each upload to ssc (this is done with Rcpp + friends and I find it super useful). It actually would suffice with including an extra .do file for testing.
