### ISSUE TITLE
Providing notifications for releases

### ISSUE THREAD

**Issue by bquistorff** [gvegayon/parallel#40]
Do we want to provide notification for releases or instructions on how to do that? See [options here](http://stackoverflow.com/questions/20839622/notifications-for-new-github-project-releases). We could steup a dedicated issue that's bumped when we release, or we could tell people to follow the RSS feed from the releases page.

**Comment by gvegayon** [comment]
using https://github.com/gvegayon/parallel/releases.atom makes more sense to me, we should include that on parallel.sthlp and the README.Rmd (README.md) file

**Comment by bquistorff** [comment]
Done at afaba6a.
