### ISSUE TITLE
Tempvar counter

### ISSUE THREAD

**Issue by bquistorff** [gvegayon/parallel#43]
Stata's handling of tempvars is a bit simplistic. We currently don't take this into account and it can cause errors. For instance if a cluster has data with a tempvar `__000000` and it tries to create a tempvar (or calls a program that does) no one (Stata nor `parallel`) remembers the parent counter so Stata starts over and gives out the name `__000000` to be created which causes an error. Having datasets with temporary variables is common if the caller of `parallel` is itself a program (and we want to facilitate other programs using `parallel`!). I have a local patch that solves this by having `parallel` get the tempname counter and then incrementing that counter in the child processes. I'll post after testing.

In diagnosing this error I examined the behavior for Stata's tempvar handling. I'm recording it here in case it's of use later.  Stata has a global tempname counter (for both `tempname` and `tempvar`) that increments with each call (and then decrements at the end of each program). At the end of a program, if any variable was created in the program that looks like a temporary variable (name `__*`) then all variables that have names that were given out by tempvar/tempname will be deleted. This is true even if tempvars were made for one dataset and then another was loaded that had the same name. That is, Stata doesn't keep track of which dataset has the specific tempvar (which, admittedly, would be difficult).

**Comment by gvegayon** [comment]
This is very interesting. Can't wait to see how you worked this out!

**Comment by bquistorff** [comment]
Done in a99ab5e.
