### ISSUE TITLE
Error when number of tasks is less than the number of clusters

### ISSUE THREAD

**Issue by bquistorff** [gvegayon/parallel#44]
In the default setup (where the dataset is divided amongst the clusters) there is an error when there are fewer observations than clusters. Ideally, we'd temporarily lower the number of clusters used. Other ways of using `parallel` might suffer similar problems, I haven't checked.

**Comment by gvegayon** [comment]
That makes sense. Although it should be with a warning. I do see some reasons why using `parallel' with less obs than clusters could be useful. The change should be on the `parallel' function directly (beginning and top/exit)

https://github.com/gvegayon/parallel/blob/master/ado/parallel.ado#L313
https://github.com/gvegayon/parallel/blob/master/ado/parallel.ado#L340
https://github.com/gvegayon/parallel/blob/master/ado/parallel.ado#L358

**Comment by bquistorff** [comment]
Done in 86fc862.
