### ISSUE TITLE
Use preserve to auto-recover from errors

### ISSUE THREAD

**Issue by bquistorff** [gvegayon/parallel#45]
Currently, in places like `parallel_do`, `parallel_bs`, `parallel_sim`, when there are errors we try to reload the dataset. This is both cumbersome (we need capture error, load dta, then delete temporary variables) and can cause small errors (I remember that depending on the error, we'd drop the sortedby). I think we should make use of the `preserve` as this will do the recovery automatically. I think once we've put together the results from the children we can cancel the preserved data with `restore, not`

**Comment by gvegayon** [comment]
Could you point out the parts of the code in which such happens specifically?

**Comment by bquistorff** [comment]
For example in `parallel.ado`, on error, we [reload](https://github.com/gvegayon/parallel/blob/e593b6332de0009827c650e7d1ab54d6bec3e9ab/ado/parallel.ado#L339) - [clean-up](https://github.com/gvegayon/parallel/blob/e593b6332de0009827c650e7d1ab54d6bec3e9ab/ado/parallel.ado#L345), [reload](https://github.com/gvegayon/parallel/blob/e593b6332de0009827c650e7d1ab54d6bec3e9ab/ado/parallel.ado#L367) - [clean-up](https://github.com/gvegayon/parallel/blob/e593b6332de0009827c650e7d1ab54d6bec3e9ab/ado/parallel.ado#L369), and in `parallel_spliter` similar [clean-up](https://github.com/gvegayon/parallel/blob/e593b6332de0009827c650e7d1ab54d6bec3e9ab/ado/parallel.ado#L197),

**Comment by bquistorff** [comment]
Done in fd81aea.
