### ISSUE TITLE
Dealing with Stata 12 string expression length limit

### ISSUE THREAD

**Issue by bquistorff** [gvegayon/parallel#48]
Stata 11/12 has a limit of 244 characters for string "expressions". This means that, for instance, when we parse long commands from the user, `regexr()` will truncate the string silently! I noticed this because the truncated string had unbalanced parantheses so got an `) required` error, but things might pass through and just be wrong. We could check and warn for this, or switch the functions to mata (we'd have to trace all the parts that work with user input), or just say that newer versions are better (Stata 13/14 has a limit of 2,000,000,000!).

**Comment by gvegayon** [comment]
That is true. I recall encountering this problem before. The issue is how
to pass the full string to mata in the form of a local :S. Yes, we should
warn about this behavior, both printing a warning and including that in the
documentation.

George G. Vega Yon
+1 (626) 381 8171
http://cana.usc.edu/vegayon

**Comment by bquistorff** [comment]
Fixed in 19ab89a.

**Comment by gvegayon** [comment]
Will this work for, say, Stata 12? Will st_local allow handling larger strings in Stata 12? (thanks by the way!)

**Comment by bquistorff** [comment]
I tested it in Stata 12 and this new code worked, whereas the previous didn't. The main constraint was on "string expressions" which I think basically means lines with `=`. For example, `loc a = regexr("...")` is affected but not `loc a "'b'"` (so not all lines with strings).

**Comment by gvegayon** [comment]
great! thanks again!

George G. Vega Yon (from mobile)
+1 626 381 8171
http://cana.usc.edu/vegayon
