### ISSUE TITLE
Include Markdown/HTML version of help

### ISSUE THREAD

**Issue by bquistorff** [gvegayon/parallel#57]
Could use [parse-smcl](https://github.com/sergiocorreia/parse-smcl) to provide it automatically. This is nice because it would allow more direct usage of GitHub for understanding the package.

**Comment by gvegayon** [comment]
Maybe setting up an actual website using github pages?

George G. Vega Yon
+1 (626) 381 8171
http://cana.usc.edu/vegayon

**Comment by bquistorff** [comment]
Could do github pages. I don't not sure when that would be good vs the wiki pages.

I was having problems with `smcl-parse` understanding indentation in code blocks ([issue](https://github.com/sergiocorreia/parse-smcl/issues/1)) so I went with `log2html` (can get from SSC).
