### ISSUE TITLE
Copy over scalars and Stata matrices

### ISSUE THREAD

**Issue by bquistorff** [gvegayon/parallel#7]
This could be added to the export globals file and just looping through different categories for st_dir. The matrices could be stored in a -mata mosave- file. The scalars could be in there too or exported to a text file like the global macros.

**Comment by bquistorff** [comment]
@gvegayon , do you remember why this issue was closed and the branch wasn't merged in? Maybe because we didn't figure out a way to copy the scalars and matrices back to the parent in a smart why (we doing only one-way might cause confusion)?

**Comment by gvegayon** [comment]
I dont remember. But it is a problem. Maybe we can add sufix to the
elements such as pll1... pll[nclusters]? No need to solve this now,
further, not sure if anyone needs it now!

George G. Vega Yon (from mobile)
+1 626 381 8171
http://cana.usc.edu/vegayon
