### ISSUE TITLE
Update global variable to remove reference to clusters

### ISSUE THREAD

**Issue by bquistorff** [gvegayon/parallel#77]
Along with the overall move from "clusters" to "children" we should probably also change `PLL_CLUSTERS` to something like `PLL_CHILDREN`. Our previous api changes we could allow backwards compatibility so do we want to do that here and define both (and deprecate the old one for later removal)?

**Comment by gvegayon** [comment]
Perhaps we could have both. Not sure though if someone is actively using those macros.

**Comment by bquistorff** [comment]
OK, let's do both and deprecate one. Let's make the change before resubmission.

**Comment by gvegayon** [comment]
OK. One thing that I've been doing lately is to use a function to retrieve a constant that I'm planning to use around, so if I make changes to it's definition or something, I just need to change it in a single place (e.g. https://github.com/USCbiostats/sluRm/blob/92d56d925774371c01d106a3f885af820d498952/R/utils.R#L202-L222). We could have something like a function as:

```stata
prog def pll_get_numbers, rclass
   if ("$PLL_CLUSTERS" != "") {
      return local ncores = $PLL_CLUSTERS
      di "PLL_CLUSTERS is deprecated. Will be removed in the future. Please use PLL_CHILDREN instead."
   } else if ("PLL_CHILDREN" != "") return local ncores = $PLL_CHILDREN
end
```

Or something like this. This could be even defined in MATA and have a wrapper in Stata both share the same thing. In the case of Stata, the function can be called at the begining of the routine, whereas in mata we can just return the number.

**Comment by bquistorff** [comment]
3bcfd8858eca1b34151ee26da05d7aa1e884a8fb
