### ISSUE TITLE
Unable to install parallel: file transmission error (checksums do not match)

### ISSUE THREAD

**Issue by aadityadar** [gvegayon/parallel#79]
Hi, I am having trouble installing -parallel-. Here's what I did:

```
net install parallel, from(https://raw.github.com/gvegayon/parallel/stable/) replace
```

and this is the error I get:
```
checking parallel consistency and verifying not already installed...
file transmission error (checksums do not match)
https://raw.github.com/gvegayon/parallel/stable/ado/parallel.ado not copied
could not copy https://raw.github.com/gvegayon/parallel/stable/ado/parallel.ado
(no action taken)
```

I am using Stata 15MP on Windows 10. What could be going wrong?

**Comment by gvegayon** [comment]
Try using the stata journal version as in #82 Another alternative is deleting the parallel files in your user dir (ado/mlib/sthlp/hlp) and re-try installing it.

**Comment by bquistorff** [comment]
There might be a network issue, so maybe trying later. (I was just able to install using this method without a problem. ) Are you able to install other packages (is the directory writable)?

You can also use the method for lower versions of Stata where a zip file of the repo is downloaded.

**Comment by aadityadar** [comment]
Hi Brian, I was able to install -parallel- on Stata 16.1/MP without any problem. I don't have v15 anymore so unable to replicate the issue. I think we can close this issue.
