### ISSUE TITLE
Could not create temporary directory in Mac OS X

### ISSUE THREAD

**Issue by mmaga** [gvegayon/parallel#9]
Dear George Vega,
Congratulations for this very useful software : )
I'm trying to run simple commands using parallel and I received the error message below.
I'm running Stata/MP 13.1 in a Mac OS X 10.9.5 (aka Mavericks).
I have skills using terminal, and unix commands. Please, let me know if you need more info. I will be very pleased to help on debugging.
Best, 
Marcelo Magalhaes

--------------------------------------------------------------------------------
. parallel setclusters 2
N Clusters: 2
Stata dir:  /Applications/Stata/StataMP.app/Contents/MacOS/StataMP

. parallel: gen id = _n

--------------------------------------------------------------------------------
Parallel Computing with Stata (by GVY)
Clusters   : 2
pll_id     : zcmiyildp1
Running at : /Users/marcelo/Projects/pos-doc-ucr-2014/dados/climate
Randtype   : datetime
Waiting for the clusters to finish...
cluster 0002 has exited without error...
could not create directory /var/folders/74/g_km5htd7ls5b179h_zh6flm0000gn/T//__pllzcmiyildp1_tmpdir0002/
                 rmdir():   693  could not remove directory
       parallel_finito():     -  function returned error
          parallel_run():     -  function returned error
                 <istmt>:     -  function returned error
r(693);

**Comment by mmaga** [comment]
I think I found the problem.

The version of parallel_run.mata available at http://fmwww.bc.edu/repec/bocode/p are under version 0.14.4.17 17apr2014. In this version, the temporary directory name is given by:

mkdir(c("tmpdir")+"/__pll"+parallelid+strofreal(i, "%04.0f"),1)

But the name should be built with "_tempdir" inbetween parallelid and i, as it is done in the version 0.14.7.22 22jul2014, available at GitHub repository:

mkdir(tmpdir+"__pll"+parallelid+"_tmpdir"+strofreal(i, "%04.0f"),1)

Which is the best way to fix it? May you help me, please?

Best,

Marcelo

**Comment by gvegayon** [comment]
Hi there, for now I recommend you to install the repo version (and ofcourse uninstall the BC one). I'll try to fix this in the comming days.

G

**Comment by mmaga** [comment]
Just got it George, exactly now!
Many many thanks!
This is a great peace of software. I’ve been doing it manually until now.
Best,
Marcelo
