### ISSUE TITLE
Stata 17 BE - Stata executable path not detected

### ISSUE THREAD

**Issue by ArnaudKunzi** [gvegayon/parallel#96]
Dear all,

/gvegayon/parallel/parallel_setstatapath.mata needs to be updated to support Stata 17 basic edition executable name.
On the BE edition, the executable path is not auto-detected and need to be manually specified:

![image](https://user-images.githubusercontent.com/22870774/135227902-e501b9a4-bd32-4300-82f9-6e04dbb530f7.png)

The basic edition is the replacement of the previous version's IC edition. Here are the system values.

![image](https://user-images.githubusercontent.com/22870774/135226034-a6187ffd-7fdd-437e-8865-cd8197feb3f1.png)
![image](https://user-images.githubusercontent.com/22870774/135228574-e0574f5e-76d0-4a09-b015-7bc97770e57f.png)

Let me know if you need more info or any help with testing!

**Comment by bquistorff** [comment]
Typically we query `c(flavor)`. Can you report what that returns? Eventually it'd be nice to know what the executable names are on Mac + Unix.

**Comment by ArnaudKunzi** [comment]
Run on stata 17BE:

![image](https://user-images.githubusercontent.com/22870774/135409240-f690d962-a84b-4255-a706-a18ad7dd8c45.png)
This tripped me up at first...

Stata's user guide [U] 5.2 gives a clarification:
![image](https://user-images.githubusercontent.com/22870774/135409766-45c54573-5383-474f-b049-15bd06057e96.png)

given that  `c(edition)`  is not defined in stata versions < 17, there will be probably a need to first check if `c(version) >=17` , and then checking  `c(edition)` or  `c(flavor)` depending on the result. A tested alternative on Stata 15MP, 16IC and 17BE is:

````di cond("`c(edition)'" != "", "`c(edition)'", "`c(flavor)'")````

and 'correctly' returns `IC` in the two first cases or `BE` in the later case.

>Eventually it'd be nice to know what the executable names are on Mac + Unix.

I would have loved to help more but I only have linux binaries up to v16 and no  Mac. Can anyone else comment on this?

**Comment by bquistorff** [comment]
I just pushed an update to `master`. Could you reinstall from `master` and see if it auto-detects the version? Thanks

**Comment by bquistorff** [comment]
Thanks for checking on this. I've updated the MacOS section accordingly.
