### ISSUE TITLE
Example 1 does not work

### ISSUE THREAD

**Issue by VickTaxiarchi** [gvegayon/parallel#98]
Hello, 

I have used the parallel package in Stata earlier with success but currently it's bringing up an error. The error is the same for every command I used it, eg parallel do, and is also the same when trying to reproduce example 1 of the help parallel Stata file: 

sysuse bplong.dta
sort patient
parallel setclusters 4
parallel, by(patient): by patient: egen max_bp = max(bp)

The error it produces is:
"cluster XXX has finished with a connection error -601- (timeout)""cluster 000X has finished with a connection error -601- (timeout)"

Same error is produced when working the example on Stata 14 on the desktop, or Stata 16 on a server. 

Any ides why this is produced and how I could overcome it please?

Best wishes
Vicky

**Comment by bquistorff** [comment]
Please specify what version of Stata and OS you are using. Also please try with latest version (uninstall parallel and then install using the GitHub installation method on the main page).

**Comment by VickTaxiarchi** [comment]
Hi,

Many thanks for the reply. V14.0 is on Windows and V16.1 on Linux. I have reinstalled parallel a few times, no change. Commands used are

Ø  ssc install parallel, replace

Ø  mata mata mlib index

Best wishes
Vicky

**Comment by bquistorff** [comment]
Please input the results of `creturn list`, also the output from one of the child logs (e.g., using `parallel printlog`) after a failure. It looks like it  can't find the Stata executable so try specifying that when using `parallel initialize`.

**Comment by VickTaxiarchi** [comment]
Hi,

Happy to do that, but already the parallel initialise command does not work for me. Please see images attached. As per the previous email, I use the option setclusters instead. Is that an issue by itself, or are these two associated?

Following on with setclusters, some things have changed. When running parallel on Stata 14 and Windows there is a different error, image attached. Rather when running on v16.1 and Linux it runs the example but fails to run my dofile, please see html attached –with details as requested.

Apologies if that is turning quite confusing. I mainly aim to be able to use the command on the Linux system.

Best wishes
Vicky

**Comment by gvegayon** [comment]
Thanks for the reply, @VickTaxiarchi. Unfortunately, no images are attached when responding to the issue through your email. You can always include images if posting through the [github site](https://github.com/gvegayon/parallel/issues/98).

**Comment by gvegayon** [comment]
@VickTaxiarchi, I think the problem is that you are using SSC's version of parallel. We have not been able to post a newer version (I think Dr. Baum was a bit busy at the time!,) so we have just kept the GitHub version up to date. I recommend you remove all source files from `personal` and other folders related to parallel. The mata library of parallel is called `lparallel.mlib,` so you'll have to remove that as well. Once you have a clean slate, proceed to install the GitHub version. Instructions to do so are [here](https://github.com/gvegayon/parallel#installation).
